import type { GetServerSideProps, NextPage } from "next";
import { unstable_getServerSession } from "next-auth";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { api_user } from "../libs/api/user";
import styles from "../styles/Home.module.css";
import { UserParam } from "../Types/User/user";
import { authOptions } from "./api/auth/[...nextauth]";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.undraw_area}>
          <Image
            src="/undraw_accept_tasks_po1c 1.svg"
            alt="Undraw picture"
            width={553}
            height={384}
          />
        </div>
        <div className={styles.texts_area}>
          <div className={styles.description}>
            <h1>
              Uma ferramenta para seu dia a dia Escreva, planeje e organize-se..
            </h1>
            <p>
              <span className={styles.span_text_area}>100% Gratuita</span> e
              online
            </p>
          </div>
          {/* <div className={styles.suporters_area}>
            <p>
              <b>Apoiadores:</b>
            </p>
            <div className={styles.suporters_image}>
              <Image
                alt="Apoiador foto"
                src="/image 13.svg"
                width={60}
                height={60}
              />
              <Image
                alt="Apoiador foto"
                src="/image 14.svg"
                width={60}
                height={60}
              />
              <Image
                alt="Apoiador foto"
                src="/image 15.svg"
                width={60}
                height={60}
              />
              <Image
                alt="Apoiador foto"
                src="/image 16.svg"
                width={60}
                height={60}
              />
            </div>
          </div> */}
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (session?.user) {
    const hasTheUser = await api_user.verifyUserExist(session.user.id);
    if (!hasTheUser) await api_user.saveLoggedUser(session.user as UserParam);
  }

  return {
    props: {
      user: session?.user || null,
    },
  };
};

export default Home;
