import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.undraw_area}>
          <Image
            src="/undraw_accept_tasks_po1c 1.svg"
            alt="Undraw picture"
            width={553}
            height={384}
          />
        </div>
        <div className={styles.texts_area}>
          <div className={styles.description}>
            <h1>
              Uma ferramenta para seu dia a dia Escreva, planeje e organize-se..
            </h1>
            <p>
              <span className={styles.span_text_area}>100% Gratuita</span> e
              online
            </p>
          </div>
          {/* <div className={styles.suporters_area}>
            <p>
              <b>Apoiadores:</b>
            </p>
            <div className={styles.suporters_image}>
              <Image
                alt="Apoiador foto"
                src="/image 13.svg"
                width={60}
                height={60}
              />
              <Image
                alt="Apoiador foto"
                src="/image 14.svg"
                width={60}
                height={60}
              />
              <Image
                alt="Apoiador foto"
                src="/image 15.svg"
                width={60}
                height={60}
              />
              <Image
                alt="Apoiador foto"
                src="/image 16.svg"
                width={60}
                height={60}
              />
            </div>
          </div> */}
        </div>
      </main>
    </div>
  );
};

export default Home;
